ignoredBuiltDependencies:
  - puppeteer

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  next-auth@>=5.0.0-beta.0 <5.0.0-beta.30: '>=5.0.0-beta.30'
